name: Reproduce Issue 4461

on:
  pull_request:
  workflow_dispatch:

jobs:
  reproduction:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [ '2.13.12', '3.3.1', '3.5.0' ] # Scala 2.13, 3 LTS (3.3.x), 3 Latest (3.5.x)
        java: [ 17, 21, 25 ]
    env:
      TERM: dumb
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            17
            21
            25-ea

      # We need to install Java 25 EA if setup-java supports it.
      # 'temurin' supports 25-ea.

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Scala Reproduction Test
        run: |
          ./gradlew :jib-gradle-plugin:integrationTest \
            --tests "com.google.cloud.tools.jib.gradle.ScalaProjectIntegrationTest" \
            -Djib.test.scalaVersion=${{ matrix.scala }} \
            -Djib.test.javaVersion=${{ matrix.java }} \
            --info
